version: "3.8"
services:
  blazegraph:
    image: lyrasis/blazegraph:2.1.5
    container_name: blazegraph
    ports:
      - "9999:8080"
    volumes:
      - blazegraph_data:/var/lib/jetty
    environment:
      JAVA_XMS: 512m
      JAVA_XMX: 2g
volumes:
  blazegraph_data:
